name: Bug Report
description: Report a bug or issue with Emoji Eraser
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug
      placeholder: When I...
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Open a file...
        2. See error...
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: Extension Version
      placeholder: e.g., 0.1.1
    validations:
      required: true
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, logs, settings, etc.
      placeholder: Add any other helpful information...
